### PR TITLE
Mark explainer as outdated

### PR DESCRIPTION
**Pull request by surma**

### CODE REVIEW

**Comment by conrad-watt** [comment]
Is this referring specifically to the text format? Which parts have become outdated?

**Comment by surma** [comment]
Yes, the text format is not up-to-date (`memory.atomic.wait32`, for example). I haven’t checked if anything else is out of date.

**Comment by conrad-watt** [comment]
We've generally been careful to keep the overview up to date, in lieu of a formal spec. The naming convention for atomics.wait was explicitly changed relatively recently (https://github.com/WebAssembly/threads/issues/145). AFAIK, `memory.atomic.wait32` is the modern mnemonic.

**Comment by surma** [comment]
I was assuming the spec is correct and not the explainer as `wabt` (or `wat2wasm --enable-threads`) more specifically recognizes `i32.atomic.wait` but _not_ `memory.atomic.wait32`.

Feel free to disregard my PR if I tackled the problem from the wrong end. I was just confused by the current state of spec vs explainer vs tooling.

**Comment by conrad-watt** [comment]
The formatted spec at https://webassembly.github.io/threads has now been updated with the modern mnemonics. I don't know if @binji has any information about wabt?

**Comment by binji** [comment]
I'm kinda surprised, since I thought I updated these names in wabt, but it seems not. I'll update.

**Comment by conrad-watt** [comment]
@surma are you happy for this to be closed now that wabt has been updated? Please let us know if you're still dealing with inconsistencies.

**Comment by surma** [comment]
Absolutely. Cheers.

**Pull request closed without merging**
