### PR TITLE
Write up alternate encoding using i8/i16 value types

### PR DESCRIPTION
**Pull request by binji**
As described here: https://github.com/WebAssembly/design/issues/1049

### CODE REVIEW

**Comment by stoklund** [comment]
This is also relevant for the SIMD `extract_lane` instructions.

**Comment by binji** [comment]
Agreed, I mention that [here](https://github.com/WebAssembly/threads/pull/14/files#diff-e12c2aa9d5fae657e6d0c78964ef2f95R578). :-)

**Comment by stoklund** [comment]
Ah, apologies. I missed that. :-)

You can get much of the same effect without introducing new value types by defining the equivalent of LLVM's SelectionDAG `zext_inreg` operators. It's basically your `i32.extend_*/i*` operator, but the input value is a `i32` where the high bits are ignored. This also maps directly to `utxb` and `uxtw` instructions on ARM.

**Comment by binji** [comment]
@stoklund good point, I'll mention that.

**Comment by binji** [comment]
Landing, assuming this accurately reflects the alternate encodings. If not, please open a new issue.

**Pull request merged**
