### PR TITLE
Change timeout from f64 ms -> i64 ns

### PR DESCRIPTION
**Pull request by binji**
See issue #36.

### CODE REVIEW

**Comment by jfbastien** [comment]
I think we need to justify why we'd diverge from https://w3ctag.github.io/design-principles/#milliseconds that @domenic points out. This is weirdly inconsistent with the JS side (both ns and using integer instead of float). I don't really understand the argument for this change: perceived implementation complexity is already there for JS, so the change saves engines zero. The discrepancy does, however, add complexity to users because JS and wasm would now be different.

**Comment by binji** [comment]
OK, please voice this opinion on the issue.

**Comment by binji** [comment]
We agreed in the CG meeting to use i64 nanoseconds. Any other issues with this PR?

**Comment by titzer** [comment]
lgtm

**Pull request merged**
